### PR TITLE
Treat yourself

### PR DESCRIPTION
**Pull request by larkceresin**
Decided to add a filter and styles that it will be removed from the images on hover (could potentially do that to other images in other sections that have a opatancy overlay in the figma design

### CODE REVIEW

**Comment by McCambley** [comment]
Looks great! 
A few thoughts on things looking at the design before merging:

1) I looks like the gaps in the grid are sometimes uneven in the figma, but I think we should keep them equal as the window size changes. Could we opt for gaps measured in pixels that change at breakpoints?
2) The padding on the cards is a nice way to maintain aspect ratio, but unfortunately it breaks when the "Male Grooming" card text wraps (I'm seeing it at 737px). Perhaps [use something like](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) `text-overflow: ellipses` here to prevent resizing. Also, I'm seeing that `padding: 43% 0;` on the cards makes them square, rather than `padding: 50% 0;`.
2) The grayscale hover effect is cool, but I think it prevents most of the coloring from showing here. It a bit more work but it looks like opting for an [black and opaque overlay](https://stackoverflow.com/a/18322705/15154619) (something with `treat-yourself__card::after`) would be best suited here. 
3) Lastly, similar to 2, I recall macksim mentioning that the background images could/should scale when a card is hovered. This bullet feels more opinionated, but it seems like [there are a few different ways to tackle that](https://css-tricks.com/zooming-background-images/) if you want to go for it.

These changes might need discussion so let me know if you want to talk thing over or brainstorm solutions!

Late edit: since the `app for you` block takes up the whole width of the page I think we need to do block level padding, rather than page level. This block will need padding as well.

**Review by McCambley — CHANGES_REQUESTED** [review]
Reviewed above

**Comment by larkceresin** [comment]
> 1. I looks like the gaps in the grid are sometimes uneven in the figma, but I think we should keep them equal as the window size changes. Could we opt for gaps measured in pixels that change at breakpoints?

👍 Will get to it!
> 2. The padding on the cards is a nice way to maintain aspect ratio, but unfortunately it breaks when the "Male Grooming" card text wraps (I'm seeing it at 737px). Perhaps [use something like](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) `text-overflow: ellipses` here to prevent resizing. Also, I'm seeing that `padding: 43% 0;` on the cards makes them square, rather than `padding: 50% 0;`.

I did notice "Male Grooming" made some changes for other things that I played around with. I didn't catch that one!
> 3. The grayscale hover effect is cool, but I think it prevents most of the coloring from showing here. It a bit more work but it looks like opting for an [black and opaque overlay](https://stackoverflow.com/a/18322705/15154619) (something with `treat-yourself__card::after`) would be best suited here.

I originally tried to implement that but had trouble with the white text. I could get the white text on the overlay with the text being in "Content" section of the CSS, but was not able to get it centered. I'll look more into it!

> 4. Lastly, similar to 2, I recall macksim mentioning that the background images could/should scale when a card is hovered. This bullet feels more opinionated, but it seems like [there are a few different ways to tackle that](https://css-tricks.com/zooming-background-images/) if you want to go for it.

I'll take a look at that! I didn't read that anywhere and I might have not caught it when looking over the recordings. I did see the original website did that.

> Late edit: since the `app for you` block takes up the whole width of the page I think we need to do block level padding, rather than page level. This block will need padding as well.

Forgot about that! Will incorporate!

**Comment by larkceresin** [comment]
Updated the above!
Did a work-around for the overlay by adding a container for the text that had a background color that will change (to allow it to go away like the brief has on hover)
And was able to incorporate the zoom!
I think I fixed the male grooming issue: But do let me know if you find a breakpoint where it messes up and I'll look into it more.

**Comment by McCambley** [comment]
Hey Jenna this is looking super good, I love the overlay implementation, creative and it looks great. That gaps look consistent and inline with the design and the zoom is working well! I've got some thoughts I'll group into related bullets. I'm sorry if this is nitpicky, hopefully it ends up being helpful and straightforward.

1) When you close the window to 750px, each card is slightly off-square, and each text element is slightly below center. 
2) When the images scale, the border-radius on the card disappears. The quick fix here is to put the BR on the container, rather than the card image, but I have another idea I'll get to.
3) This is not in the design but I think something like a .3 ease transition on the overlay and image scale would look nice. 

Ok, the idea, I'll admit I'm sleepy so in lieu of rambling on too long I [built a thing](https://codepen.io/mccambley/pen/bGqQveM) that will explain way better what I'd type. 

In short, a few things:
1) The brief uses non-square images but why not just use square images? Maybe crop them or see if figma can export cropped images? Prim-u might want to use non-square photos down the line, but that can be a later thing. I think square images will reduce headaches from maintaining aspect ratios
2) Nesting the image as an `img` can provide a bit more flexibility towards adding animations for hover effects
3) I put some transitions in the example and I use a similar version of your text-box-image-overlay
4) I used absolute positioning... seems generally frowned upon but it's within a very contained space and I think it's fair game here. 

Lastly, I think it's fine to merge this and continue working while we build the page out? I love the feedback process but I don't want it to slow down the process of getting blocks on the page to work around. If you agree and think that's okay, I say merge this puppy, otherwise I'm down to hop on a call tomorrow or later this week and talk about things before a merge!

**Comment by larkceresin** [comment]
@McCambley I really appreciate all the feedback!
Implemented some more changes.
I put the radius on the container, changed to use img rather than background-image. I made transitions be 1s since I found it a bit more relaxing to have it kind of ease into it more than be as fast. And just the images are being zoomed on!!! 

I know that I'm not good at getting text centered and I'd rather work on that bit later when we're ironing things out if everything else is good to go. The amount of time I've worked on getting it as close as I have is more already than I would like to have done.

**Comment by McCambley** [comment]
@larkceresin Looks awesome Jenna. The image scaling is looking wonderful on each image and the overlay is smooth. 
Re: centering text: I definitely get that. Let's merge this so that things are on the page and we can come back to it later as things go. I'm with you, the first section  (header for me) definitely took more time than anticipated and it doesn't seem  productive to get bogged down on first steps at the expense of the bigger picture. 

**Some final FB as I merge:** 

Centering text: If you remove the modifiers on the "Male Grooming" card, throw `display: flex;` and `align-items: center` on `.treat-yourself__text` things should be good to go.

General block spacing: double check the block padding as breakpoints increase (side padding is 40px and 60px at midsize and large screens respectively) and remove the default margins from text elements to get more intentional spacing. Heading text can have margins of 0px on top (depending on the eventual padding on the above block) and 60px on the bottom. Card text can have no margins. 

Opinion stuff: the images seem to get a bit blurry when they scale so large, it might maintain the quality a bit more with a more subtle scale of 1.05 or so. I love the 1 second though, definitely more calm. 

Looks wonderful, excited to keep building, thanks for hearing and working with all the feedback :)

**Pull request merged**
